# Generated by Django 2.1.2 on 2018-11-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries',
            name='data_type',
            field=models.TextField(default='newcomers'),
            preserve_default=False,
        ),
    ]
